# Generated by Django 6.1 on 2026-09-02 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NSQFTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qp_code', models.CharField(help_text='Official QP Code, e.g. ELE/Q3102', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Official Trade / QP Name', max_length=200)),
                ('sector', models.CharField(help_text='Sector Skill Council / Domain', max_length=100)),
                ('nsqf_level', models.IntegerField(default=3, help_text='NSQF Level from 1 to 7')),
                ('min_education', models.CharField(default='8th Pass', help_text='Minimum education qualification requirement', max_length=100)),
                ('wage_vs_self_score', models.FloatField(default=0.5, help_text='0.0 = Pure Wage Employment, 1.0 = Pure Self-Employment / Micro-enterprise')),
                ('traditional_synergy_tags', models.JSONField(default=list, help_text='List of traditional family occupation keywords synergizing with this QP')),
                ('district_demand_tags', models.JSONField(default=list, help_text='List of regional district economy profile tags')),
                ('avg_monthly_income_inr', models.IntegerField(default=18000, help_text='Projected monthly wage/income in INR post certification')),
                ('duration_hours', models.IntegerField(default=360, help_text='Course duration in total training hours')),
                ('description', models.TextField(blank=True)),
                ('key_modules', models.JSONField(default=list, help_text='Core technical and soft skill modules covered')),
                ('prerequisite_skills', models.JSONField(default=list, help_text='Foundational baseline skills')),
            ],
            options={
                'verbose_name': 'NSQF Trade Qualification Pack',
                'verbose_name_plural': 'NSQF Trade Qualification Packs',
                'ordering': ['sector', 'nsqf_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous Beneficiary', max_length=120)),
                ('age', models.IntegerField(default=24)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(default='Varanasi', max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('preferred_language', models.CharField(choices=[('hi', 'Hindi (हिन्दी)'), ('ta', 'Tamil (தமிழ்)'), ('te', 'Telugu (తెలుగు)'), ('mr', 'Marathi (मराठी)'), ('or', 'Odia (ଓଡ଼ିଆ)'), ('bn', 'Bengali (বাংলা)'), ('en', 'English')], default='hi', max_length=10)),
                ('education_level', models.CharField(default='8th Pass', help_text='Dim 1: Educational Background', max_length=100)),
                ('family_occupation', models.CharField(default='Handloom & Textiles', help_text='Dim 2: Traditional Family Occupation', max_length=150)),
                ('current_livelihood', models.CharField(default='Daily Wage Helper', help_text='Dim 3: Current Livelihood', max_length=150)),
                ('primary_skills', models.JSONField(default=list, help_text='Dim 4: Skills & Interests extracted from dialogue')),
                ('mobility_constraint', models.CharField(default='Within District HQ', help_text='Dim 5: Physical & Geographic Mobility constraints', max_length=100)),
                ('employment_preference', models.CharField(default='Self-Employed / Micro-Enterprise', help_text='Dim 6: Self vs Wage Employment Preference', max_length=100)),
                ('district_economy', models.CharField(default='Rural Agri-Textile Hub', help_text='Dim 7: Local District Economic Realities', max_length=150)),
                ('dimension_vector', models.JSONField(blank=True, default=dict, help_text='Calculated 7-dimension normalized weights')),
                ('survey_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_trades', models.ManyToManyField(blank=True, related_name='recommended_beneficiaries', to='livelihood_app.nsqftrade')),
            ],
            options={
                'verbose_name': 'Beneficiary Profile',
                'verbose_name_plural': 'Beneficiary Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(help_text='Unique Center Code, e.g. PMAJAY-TC-UP-01', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Center name', max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(default=28.6139)),
                ('longitude', models.FloatField(default=77.209)),
                ('hostel_available', models.BooleanField(default=False)),
                ('pm_ajay_funded', models.BooleanField(default=True, help_text='Funded under PM-AJAY Special Central Assistance')),
                ('trades_offered', models.ManyToManyField(blank=True, related_name='training_centers', to='livelihood_app.nsqftrade')),
            ],
            options={
                'verbose_name': 'PM-AJAY Skill Training Center',
                'verbose_name_plural': 'PM-AJAY Skill Training Centers',
                'ordering': ['state', 'district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('detected_language', models.CharField(default='hi', max_length=20)),
                ('confidence_score', models.FloatField(default=0.92)),
                ('step_number', models.IntegerField(default=1)),
                ('extracted_dimension', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_logs', to='livelihood_app.beneficiary')),
            ],
            options={
                'verbose_name': 'Voice Conversation Log',
                'verbose_name_plural': 'Voice Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
